//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Accounting.data.ICSRTallyDb
{
    using System;
    using System.Collections.Generic;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Validation;
    using System.Threading;
    using System.Threading.Tasks;

    public partial class ICSRDBTALLYEntities : DbContext,IICSRDBTALLYEntities
    {
        public ICSRDBTALLYEntities()
            : base("name=ICSRDBTALLYEntities")
        {
        }
        public virtual DbSet<Ledger> Ledgers { get; set; }
        public virtual DbSet<Voucher> Vouchers { get; set; }
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            //throw new UnintentionalCodeFirstException();

            
        }

        void IICSRDBTALLYEntities.Dispose(bool disposing)
        {
            throw new NotImplementedException();
        }

        void IICSRDBTALLYEntities.OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new NotImplementedException();
        }

        bool IICSRDBTALLYEntities.ShouldValidateEntity(DbEntityEntry entityEntry)
        {
            throw new NotImplementedException();
        }

        DbEntityValidationResult IICSRDBTALLYEntities.ValidateEntity(DbEntityEntry entityEntry, IDictionary<object, object> items)
        {
            throw new NotImplementedException();
        }

        

     
    }
}
