//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Accounting.data.databasemodel2
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccTransaction
    {
        public string TransNO { get; set; }
        public string INSTID { get; set; }
        public string ProjectNo { get; set; }
        public Nullable<int> voucherType { get; set; }
        public string voucherNo { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<System.DateTime> bankDate { get; set; }
        public Nullable<decimal> currentBal { get; set; }
        public Nullable<decimal> AvailableBal { get; set; }
        public string ChequeNO { get; set; }
        public string narration { get; set; }
        public string Remarks { get; set; }
        public System.DateTime TransCreated { get; set; }
        public Nullable<System.DateTime> TransUpdated { get; set; }
        public bool TransCommited { get; set; }
    }
}
