//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Accounting.data.databasemodel2
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImprestMaster
    {
        public string InstituteId { get; set; }
        public string CoordinatorName { get; set; }
        public string Department { get; set; }
        public string Designation { get; set; }
        public decimal BankAccountNo { get; set; }
        public decimal Amount { get; set; }
        public Nullable<decimal> Limit { get; set; }
    }
}
