//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Accounting.data.databasemodel2
{
    using System;
    using System.Collections.Generic;
    
    public partial class VoucherSubType
    {
        public int SubTypeID { get; set; }
        public Nullable<int> VoucherTypeId { get; set; }
        public string VoucherType { get; set; }
    }
}
