
CREATE FUNCTION [dbo].[GENERATERECOUPID] (@ACCNO NVARCHAR(14))
RETURNS NVARCHAR(33)
AS
BEGIN
DECLARE @RECOUPID NVARCHAR(33)
SET @RECOUPID= 'RE'+RIGHT('0000' + Ltrim(Rtrim(@ACCNO)), 14)+
CONVERT(NVARCHAR(4),DATEPART(YEAR, GETDATE()))+
RIGHT('00' + CONVERT(NVARCHAR(2), DATEPART(MONTH, GETDATE())), 2)+
RIGHT('00' + CONVERT(NVARCHAR(2), DATEPART(DAY, GETDATE())), 2)+
RIGHT('00' + CONVERT(NVARCHAR(2), DATEPART(HOUR, GETDATE())), 2)+
RIGHT('00' + CONVERT(NVARCHAR(2), DATEPART(minute, GETDATE())), 2)+
RIGHT('00' + CONVERT(NVARCHAR(2), DATEPART(second, GETDATE())), 2)+
RIGHT('000' + CONVERT(NVARCHAR(3), DATEPART(millisecond, GETDATE())), 3)
RETURN @RECOUPID
END
